# Generated by Django 4.1.10 on 2023-09-05 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("curriculum", "0003_coursecompletedmodel_coursemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("content", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="CourseCompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("date", models.DateField(default=datetime.datetime.today)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350)),
                ("link", models.URLField(max_length=350)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.course",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="coursecompletedmodel",
            name="CourseModel",
        ),
        migrations.DeleteModel(
            name="CourseLinkModel",
        ),
        migrations.DeleteModel(
            name="CourseCompletedModel",
        ),
        migrations.DeleteModel(
            name="CourseModel",
        ),
    ]
