# Generated by Django 4.1.10 on 2023-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0005_course_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="content",
            field=models.TextField(max_length=10000),
        ),
    ]
