# Generated by Django 4.1.10 on 2023-09-09 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0006_alter_course_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecompleted",
            name="status",
        ),
    ]
