# Generated by Django 4.1.10 on 2023-09-09 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0007_remove_coursecompleted_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecompleted",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
